### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by vincentdelitz** [corbado/nextjs-login-page#1]
- [x] please add an `.env.example` file, so that things can be started out-of-the-box after the right values have been filled (basicall you've written about that in the README already but you can add it as a separate file)
- [x] Please add a quick explainer how to install / start the MongoDB instance to the README
- [x] Rename "Email&Password-based Authentication" to only "Password-based Authentication" everywhere
- [x] Reorder the authentication methods in the same order as they are described in the blog post:
![image](https://github.com/user-attachments/assets/95d4d3f8-8fda-42d4-a779-8b289716b6b5)

- [ ] What does the signup button stand for? We should explain that as well or if the process is to create an account first before it can be used for logins. That's not clear to me.
- [x] Can you provide me with sample values for the `.env.local` file, so that I can quickly try things myself?
- [ ] Do we store / connect any information from Social login (via Google) in the MongoDB database?
- [ ] (can also be added in the text of the blog post) -> why did you decide to use NextAuth.js? What was the reason against doing it completely yourself or using another library? I think we should briefly provide the reasoning behind this decision.
- [ ] Can new user accounts only be created with a password? If yes, we should make the user creation process independent from the password / authentication method.

**Comment by AmalADDAD98** [comment]
@vincentdelitz Regarding this question, What does the signup button stand for? 

The signup button is part of the Password-based authentication only.
I added a link in the login component for the signup and removed it from the home page.

![image](https://github.com/user-attachments/assets/acde1e56-3736-4b2e-aea6-2bb306bc7c9a)


The process of the signup/sign-in with password is already explained. Should it need some clarification?

**Comment by AmalADDAD98** [comment]
@vincentdelitz Regarding this question, Do we store/connect any information from Social login (via Google) in the MongoDB database?

For the Google auth, we are not storing any data related to the authenticated user. We only manage the sessions.

**Comment by AmalADDAD98** [comment]
@vincentdelitz regarding this  question : Can new user accounts only be created with a password? If yes, we should make the user creation process independent from the password / authentication method.


The creation of the user accounts is only part of the Password-based authentication. The users don't need to create an account for the other login methods (OTP, Google auth, and TOTP). 
The implementation of all the login methods is independent of each other.

**Comment by AmalADDAD98** [comment]
@vincentdelitz  Regarding this point : (can also be added in the text of the blog post) -> why did you decide to use NextAuth.js? What was the reason against doing it completely yourself or using another library? I think we should briefly provide the reasoning behind this decision.

I decided to use NextAuth.js for the  Google login integration because it simplifies the authentication process. NextAuth.js provides built-in support for Google and other providers, handling the complex OAuth flow and security concerns.

**Comment by vincentdelitz** [comment]
> @vincentdelitz Regarding this question, What does the signup button stand for?
> 
> The signup button is part of the Password-based authentication only. I added a link in the login component for the signup and removed it from the home page.
> 
> ![image](https://private-user-images.githubusercontent.com/173041305/348635831-acde1e56-3736-4b2e-aea6-2bb306bc7c9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzM4NzYsIm5iZiI6MTcyMTAzMzU3NiwicGF0aCI6Ii8xNzMwNDEzMDUvMzQ4NjM1ODMxLWFjZGUxZTU2LTM3MzYtNGIyZS1hZWE2LTJiYjMwNmJjN2M5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwODUyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTQ2NDlkNjcyZDIwYTRhOTZiMjYyMTZmMGNlODdhNTAyNzlkMTFkYjM5M2EzNzg5Y2JhNzQ1NTJmMDE3MmMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S9aqS_s36WJWg9dDuzILtdgLL2vKklBowwSX4v5umz4)
> 
> The process of the signup/sign-in with password is already explained. Should it need some clarification?

I see, thanks!

I'm thinking more general, what would be more helpful for developers:
1. Connect all authentication methods (so not only passwords) to users and account creation or
2. Keep it as you have changed it now, so that it's really only the users (then we would still need to add a short paragraph to our blog post explaining why the sign-up only works for password-based authentication).

What do you think? What's your preference?

**Comment by vincentdelitz** [comment]
> @vincentdelitz regarding this question : Can new user accounts only be created with a password? If yes, we should make the user creation process independent from the password / authentication method.
> 
> The creation of the user accounts is only part of the Password-based authentication. The users don't need to create an account for the other login methods (OTP, Google auth, and TOTP). The implementation of all the login methods is independent of each other.

See my other comment

**Comment by vincentdelitz** [comment]
> @vincentdelitz Regarding this point : (can also be added in the text of the blog post) -> why did you decide to use NextAuth.js? What was the reason against doing it completely yourself or using another library? I think we should briefly provide the reasoning behind this decision.
> 
> I decided to use NextAuth.js for the Google login integration because it simplifies the authentication process. NextAuth.js provides built-in support for Google and other providers, handling the complex OAuth flow and security concerns.

I fully understand that. Then, we would just need to add this reasoning and also why you didn't go for another library to the blog post, so that other developers understand this as well. Can you please add this?

**Comment by AmalADDAD98** [comment]
> > @vincentdelitz Regarding this point : (can also be added in the text of the blog post) -> why did you decide to use NextAuth.js? What was the reason against doing it completely yourself or using another library? I think we should briefly provide the reasoning behind this decision.
> > I decided to use NextAuth.js for the Google login integration because it simplifies the authentication process. NextAuth.js provides built-in support for Google and other providers, handling the complex OAuth flow and security concerns.
> 
> I fully understand that. Then, we would just need to add this reasoning and also why you didn't go for another library to the blog post, so that other developers understand this as well. Can you please add this?

@vincentdelitz Yes, sure. I will add the reasoning in the Word document.

**Comment by AmalADDAD98** [comment]
> > @vincentdelitz Regarding this question, What does the signup button stand for?
> > The signup button is part of the Password-based authentication only. I added a link in the login component for the signup and removed it from the home page.
> > ![image](https://private-user-images.githubusercontent.com/173041305/348635831-acde1e56-3736-4b2e-aea6-2bb306bc7c9a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzM4NzYsIm5iZiI6MTcyMTAzMzU3NiwicGF0aCI6Ii8xNzMwNDEzMDUvMzQ4NjM1ODMxLWFjZGUxZTU2LTM3MzYtNGIyZS1hZWE2LTJiYjMwNmJjN2M5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwODUyNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZTQ2NDlkNjcyZDIwYTRhOTZiMjYyMTZmMGNlODdhNTAyNzlkMTFkYjM5M2EzNzg5Y2JhNzQ1NTJmMDE3MmMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S9aqS_s36WJWg9dDuzILtdgLL2vKklBowwSX4v5umz4)
> > The process of the signup/sign-in with password is already explained. Should it need some clarification?
> 
> I see, thanks!
> 
> I'm thinking more general, what would be more helpful for developers:
> 
> 1. Connect all authentication methods (so not only passwords) to users and account creation or
> 2. Keep it as you have changed it now, so that it's really only the users (then we would still need to add a short paragraph to our blog post explaining why the sign-up only works for password-based authentication).
> 
> What do you think? What's your preference?

@vincentdelitz From my understanding of the requirements from the beginning, my approach was to implement different authentication methods independently. In my point of view, this approach offers simplicity and modularity. Moreover, it makes managing and maintaining each authentication method easier.

Refactoring the implementation of all the auth methods now can be quite complex and also it may require time to refactor and test everything together.

I think after the change I made in the password-based authentication, the process of each method is clear and consistent. What do you think?

**Comment by vincentdelitz** [comment]
@AmalADDAD98 all fine for me, let's just publish it
